version: '3.8'
services:
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mgnrega
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  redis:
    image: redis:6-alpine
    restart: unless-stopped
    ports:
      - '6379:6379'

  backend:
    build: ./backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    environment:
      # Override Redis host in Docker Compose network
      REDIS_URL: "redis://redis:6379"
      # Use local Postgres service and disable channel binding
      DATABASE_URL: "postgresql://user:password@db:5432/mgnrega?sslmode=disable"
    depends_on:
      - db
      - redis
    ports:
      - '5000:5000'
    # Run built production server
    command: npm start

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - '80:80'

volumes:
  db-data: